"""add employee, system_config, audit_log, llm_call

Revision ID: 595e12d66a37
Revises: 4cebb37b14d6
Create Date: 2026-05-14 06:26:08.594571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '595e12d66a37'
down_revision: Union[str, Sequence[str], None] = '4cebb37b14d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_key', sa.Text(), nullable=True),
    sa.Column('field_path', sa.Text(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('audit_log_target', 'audit_log', ['target_type', 'target_key', 'timestamp'], unique=False)
    op.create_index('audit_log_time', 'audit_log', ['timestamp'], unique=False)
    op.create_table('employee',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('role_desc', sa.Text(), nullable=True),
    sa.Column('feishu_app_id', sa.Text(), nullable=True),
    sa.Column('feishu_app_secret', sa.Text(), nullable=True),
    sa.Column('agent_port', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('persona', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('behavior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('agent_port')
    )
    op.create_table('llm_call',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('employee_key', sa.Text(), nullable=True),
    sa.Column('call_type', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('llm_call_emp_time', 'llm_call', ['employee_key', 'timestamp'], unique=False)
    op.create_index('llm_call_time', 'llm_call', ['timestamp'], unique=False)
    op.create_table('system_config',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('default_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('global_prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('id = 1', name='system_config_singleton'),
    )

    # Trigger: notify config_changed channel on employee/system_config writes
    op.execute("""
        CREATE OR REPLACE FUNCTION notify_config_change() RETURNS trigger AS $$
        BEGIN
          PERFORM pg_notify(
            'config_changed',
            json_build_object(
              'table', TG_TABLE_NAME,
              'op',    TG_OP,
              'key',   COALESCE(NEW.key, OLD.key)
            )::text
          );
          RETURN COALESCE(NEW, OLD);
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_employee_change
          AFTER INSERT OR UPDATE OR DELETE ON employee
          FOR EACH ROW EXECUTE FUNCTION notify_config_change();
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION notify_system_config_change() RETURNS trigger AS $$
        BEGIN
          PERFORM pg_notify(
            'config_changed',
            json_build_object('table', 'system_config', 'op', TG_OP, 'key', 'global')::text
          );
          RETURN NEW;
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_system_config_change
          AFTER INSERT OR UPDATE ON system_config
          FOR EACH ROW EXECUTE FUNCTION notify_system_config_change();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_system_config_change ON system_config")
    op.execute("DROP TRIGGER IF EXISTS trg_employee_change ON employee")
    op.execute("DROP FUNCTION IF EXISTS notify_system_config_change()")
    op.execute("DROP FUNCTION IF EXISTS notify_config_change()")
    op.drop_table('system_config')
    op.drop_index('llm_call_time', table_name='llm_call')
    op.drop_index('llm_call_emp_time', table_name='llm_call')
    op.drop_table('llm_call')
    op.drop_table('employee')
    op.drop_index('audit_log_time', table_name='audit_log')
    op.drop_index('audit_log_target', table_name='audit_log')
    op.drop_table('audit_log')
